### ISSUE TITLE
Project Picker does not open when there are no projects supplied

### ISSUE THREAD

**Issue by madebysid** [prisma/lens#196]
READ: it needs an empty state

**Comment by luanvdw** [comment]
@julietacurdi @madebysid 

Given the nature of the project picker and where it is being used (for example the Header) I just want to open the discussion of what our desired outcome is for the scenario when a user does not have a project. (i.e. an empty state for the project picker)

Here I have one project

![with_project](https://user-images.githubusercontent.com/6928171/125290408-90a31e80-e320-11eb-9a08-7164f1325278.png)

making the dropdown a great tool to indicate the active project as well as where I, as a user, could possibly find and switch between projects.

When I have no projects, the following occurs,

![with_no_projects](https://user-images.githubusercontent.com/6928171/125290621-ce07ac00-e320-11eb-94d2-29cb29304855.png)

The project picker has nothing to show, but the screen beneath clearly indicates to the user that a project needs to be created.

As such I played around with a few options, as to what we could do for an empty state with the project picker.

![Screenshot 2021-07-12 at 14 39 10](https://user-images.githubusercontent.com/6928171/125290904-1921bf00-e321-11eb-8025-c119fdbba2f3.png)

this option could be considered consistent with how the component works when it does have projects to choose from, but felt a bit unintuitive as the user would need to click twice in order to then create a project.

So I did the following;

![Screenshot 2021-07-12 at 14 42 47](https://user-images.githubusercontent.com/6928171/125291086-4ec6a800-e321-11eb-8a05-c11d1ea9197f.png)

Allowing the user to quickly select the only action that they can in any case make when there is no projects and that is to create a new project,

but with the view we are presenting the user when they have no projects would it perhaps not be overkill to have a "Create a new project" CAT in the header and the view beneath the header?

Unless the Project Picker needs to be used else where in a different context as well?

Either way I just wanted to discuss what we would consider the desired outcome here before submitting a PR
