### ISSUE TITLE
Add button variant to link styling

### ISSUE THREAD

**Issue by luanvdw** [prisma/lens#352]
The `<Link />` component does not accommodate button styling and using a `<Button />` is not accessible.

**Comment by carlagn** [comment]
This issue should be accommodated by the `WebsiteButton` component.

Using it with a `href` attribute instead of an action `onClick` renders an `<a />` element on the DOM. `type` prop defines the styling, defaulting to button styling, whereas `type="link"` renders a `<a />` element with link styling.

**Comment by nilubava** [comment]
Not relavant for Webdev
