### ISSUE TITLE
Change color on positive disabled button to enhance affordance

### ISSUE THREAD

**Issue by petradonka** [prisma/lens#393]
**Issue**
- Positive disabled button has a color that doesn't make it clear that is actually disabled

**What to do**
- Change button's color
> -  current green to green200 and text color to white to make more clear that the state is disabled

(Originally https://github.com/prisma/pdp-control-plane/issues/2241)

**Comment by sof-andrade** [comment]
Currently reviewing update with lens team 

- Now the button is on green300, I’m proposing taking it to green200
- And the text to change from gray100 to white
- I’m attaching an example of how the button would like, as well as some examples in context to see why we need this and how the new color would work
- examples of how it would work attached next

![Image](https://user-images.githubusercontent.com/101594161/167176124-bf7f2f2b-6c9a-4c48-8d13-4caf9978b4aa.png)
----
![Image](https://user-images.githubusercontent.com/101594161/167176165-9703c804-91f3-4344-b703-0f8d23948415.png)
-----
![Image](https://user-images.githubusercontent.com/101594161/167176188-25aaf8d4-2986-4aac-ad6b-e541c05028bf.png)

**Comment by sof-andrade** [comment]
We've reviewed this with Juli and saw that contrast of those greens is not that good. So we decided to only have one style for disabled buttons, and just keep the same for secondary button. This brings consistency and much needed simplicity to the system 🌈

So positive button will now have its disabled status style with Gray200 for fill, and Gray 500 for text
This issue is now close and ready to implement, will create corresponding task next 


Leaving some images for reference
![Image](https://user-images.githubusercontent.com/101594161/167199436-591118a7-2c9f-4935-ac9a-08cfe1316422.png)
![Image](https://user-images.githubusercontent.com/101594161/167199511-a497c260-f65c-4bff-8b9f-3ac810b5d624.png)
![Image](https://user-images.githubusercontent.com/101594161/167199517-a71abc5d-2982-4e1b-ad2e-0d8e5562b76c.png)
