### ISSUE TITLE
Add an `icon` prop to Button

### ISSUE THREAD

**Issue by madebysid** [prisma/lens#80]
Icon buttons are pretty common (in general), although currently we have only 1: Login With Github button on Cloud.

It'd be great if this was supported OOTB rather than having to build it outside (and deal with spacing etc.)

**Comment by luanvdw** [comment]
Hi @madebysid  👋 

To make sure I understand correctly, is your aim for the Button component to be updated so that it can support receiving an Icon as a prop that would then render a Button in the following manner?

*screenshot attached

![button_example](https://user-images.githubusercontent.com/6928171/116108870-98094300-a6b4-11eb-91c2-d8060c17af69.png)

**Comment by madebysid** [comment]
Hey @luanvdw yep, that's exactly what I mean! Are you interested in doing this? :D

**Comment by luanvdw** [comment]
@madebysid sure thing! I will send a PR shortly to get the update going 👍

**Comment by madebysid** [comment]
Awesome! Thanks for that :D

**Comment by madebysid** [comment]
This was done by Luan in https://github.com/prisma/lens/pull/81, closing!
